baseURL = "https://jmonkeyengine.org"
languageCode = "en-us"
title = "jMonkeyEngine"
summarylength = 60
enableRobotsTXT = true
ignoreErrors = ["error-output-taxonomy"]
pygmentsCodeFences=false
disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 9

[markup.goldmark.renderer]
  hardWraps = true
  unsafe= true
  
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  hostname="jmonkeyengine.org"
  store=true
  libraryEnabled=false
  libraryApiBase="https://backend.jmonkeyengine.org"
  initializerUrl="https://start.jmonkeyengine.org"
  libraryHiddenTopics=[
    "jmonkey",
    "jmonkeyengine",
    "jmonkeyengine3",
    "jme3",
    "java",
    "java-library",
    "jvm",
    "jvm-library",
    "library",
    "libraries",
    "open-source",
    "opensource"
  ]

[params.donate]
  defaultFundIcon = "fa-solid fa-circle-dollar-to-slot"

[params.donate.fundIcons]
  jmonkeyengine = "fa-solid fa-heart"
  jmonkeyengine-hosting = "fa-solid fa-server"
  jmonkeyengine-bountry-trial = "fa-solid fa-hand-holding-dollar"

[params.community.exclusions]
  backers = []
  contributors = ["Copilot", "dependabot[bot]", "jaime-jmebot"]

[outputs]
  home = ["HTML"]
  section = ["HTML","RSS"]
  page = ["HTML","JSON"]
