baseURL = "https://jmonkeyengine.org"
languageCode = "en-us"
title = "jMonkeyEngine"
summarylength = 60
enableRobotsTXT = true
ignoreErrors = ["error-output-taxonomy"]
pygmentsCodeFences=false
disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 9

[markup.goldmark.renderer]
  hardWraps = true
  unsafe= true
  
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  hostname="jmonkeyengine.org"

[params.community.exclusions]
  backers = []
  contributors = ["Copilot", "dependabot[bot]"]

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML","JSON"]
